In [1]:
import numpy as np
import pandas as pd

In [2]:
boston = pd.read_csv("training_boston_x_y_train.csv")

In [3]:
boston.shape

(379, 14)

In [4]:
boston.describe()

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
count,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000,379.000000
mean,0.019628,0.002455,0.036170,0.028955,0.028775,0.032202,0.038395,-0.001288,0.043307,0.043786,0.019218,-0.015785,0.018418,22.609499
std,1.067490,1.000813,1.017497,1.048995,0.999656,1.001174,0.985209,1.027803,1.016265,1.019974,1.000296,1.015797,1.015377,9.389647
min,-0.417713,-0.487722,-1.516987,-0.272599,-1.465882,-3.880249,-2.335437,-1.267069,-0.982843,-1.313990,-2.707379,-3.883072,-1.531127,5.000000
25%,-0.408171,-0.487722,-0.867691,-0.272599,-0.878475,-0.571480,-0.768994,-0.829872,-0.637962,-0.755697,-0.488039,0.197588,-0.828856,16.700000
50%,-0.383729,-0.487722,-0.180458,-0.272599,-0.144217,-0.103479,0.338718,-0.329213,-0.523001,-0.440915,0.297977,0.374827,-0.161629,21.100000
75%,0.055208,0.156071,1.015999,-0.272599,0.628913,0.529069,0.911243,0.674172,1.661245,1.530926,0.806576,0.429868,0.647173,25.750000
max,9.941735,3.804234,2.422565,3.668398,2.732346,3.555044,1.117494,3.960518,1.661245,1.798194,1.638828,0.441052,3.409999,50.000000

In [5]:
boston.columns

Index(['# CRIM', ' ZN', ' INDUS', ' CHAS', ' NOX', ' RM', ' AGE', ' DIS',
       ' RAD', ' TAX', ' PTRATIO', ' B', ' LSTAT', ' Y'],
      dtype='object')

In [6]:
def gd(data, learning_rate, number_of_iterations):
    slopes = np.zeros(data.shape[1])
    new_slopes = np.zeros(data.shape[1])
    for i in range(number_of_iterations):
        for j in range(len(slopes)):
            new_slopes[j] = slopes[j] - learning_rate*step_gradient(data,slopes,j)
        slopes = new_slopes
        print(i,"th iteration with cost ",cost(data,slopes))
    return slopes

In [7]:
def step_gradient(data, slopes, j):
    M = len(data)
    N = len(slopes)
    if j==(N-1):
        change = 0
        for i in range(M):
            pred = 0
            for k in range(N-1):
                pred += slopes[k]*data.iloc[i, k]
            pred += slopes[N-1]
            change += (-2/M) * (data.iloc[i, N-1] - pred)*1
        return change
    else:
        change = 0
        for i in range(M):
            pred = 0
            for k in range(N-1):
                pred += slopes[k]*data.iloc[i, k]
            pred += slopes[N-1]
            change += (-2/M) * (data.iloc[i, N-1] - pred)*data.iloc[i, j]
        return change

In [8]:
def cost(data, slopes):
    N = len(slopes)
    M = len(data)
    total_cost = 0
    for i in range(M):
        pred = 0
        for j in range(N-1):
            pred += slopes[j]* data.iloc[i,j]
        pred += slopes[N-1]
        total_cost += (data.iloc[i,N-1] - pred)**2
    return total_cost

In [9]:
def run(data):
    learning_rate = 0.1
    number_of_iterations = 100
    return gd(data, learning_rate, number_of_iterations)

In [10]:
slopes = run(boston)

0 th iteration with cost  141837.0949161156
1 th iteration with cost  93164.40751992383
2 th iteration with cost  62758.937106867794
3 th iteration with cost  43550.60956174944
4 th iteration with cost  31362.237677896414
5 th iteration with cost  23599.182473403656
6 th iteration with cost  18634.965908652528
7 th iteration with cost  15445.997986981587
8 th iteration with cost  13386.198594009598
9 th iteration with cost  12046.703837494335
10 th iteration with cost  11168.142034393719
11 th iteration with cost  10585.592252205808
12 th iteration with cost  10193.947344848126
13 th iteration with cost  9926.060378155582
14 th iteration with cost  9738.92419060618
15 th iteration with cost  9604.912640980441
16 th iteration with cost  9506.2189279965
17 th iteration with cost  9431.317627585782
18 th iteration with cost  9372.710233048736
19 th iteration with cost  9325.486182212708
20 th iteration with cost  9286.402862523844
21 th iteration with cost  9253.296400992487
22 th iteration with cost  9224.703596865347
23 th iteration with cost  9199.618821001779
24 th iteration with cost  9177.337313152259
25 th iteration with cost  9157.35386974263
26 th iteration with cost  9139.297101442926
27 th iteration with cost  9122.88657488253
28 th iteration with cost  9107.904709201328
29 th iteration with cost  9094.178210997577
30 th iteration with cost  9081.565695475747
31 th iteration with cost  9069.949336015403
32 th iteration with cost  9059.22915049918
33 th iteration with cost  9049.319024723127
34 th iteration with cost  9040.143889571516
35 th iteration with cost  9031.637672371646
36 th iteration with cost  9023.741774281742
37 th iteration with cost  9016.403910543564
38 th iteration with cost  9009.577205520438
39 th iteration with cost  9003.219470272194
40 th iteration with cost  8997.292613822794
41 th iteration with cost  8991.762154644453
42 th iteration with cost  8986.596809041836
43 th iteration with cost  8981.768139892129
44 th iteration with cost  8977.250253759046
45 th iteration with cost  8973.019537509981
46 th iteration with cost  8969.054427719931
47 th iteration with cost  8965.335207663025
48 th iteration with cost  8961.84382778237
49 th iteration with cost  8958.563746327503
50 th iteration with cost  8955.479787447615
51 th iteration with cost  8952.578014486877
52 th iteration with cost  8949.84561658628
53 th iteration with cost  8947.270806981824
54 th iteration with cost  8944.842731620032
55 th iteration with cost  8942.55138690192
56 th iteration with cost  8940.38754552465
57 th iteration with cost  8938.342689523492
58 th iteration with cost  8936.408949729683
59 th iteration with cost  8934.579050956081
60 th iteration with cost  8932.846262305735
61 th iteration with cost  8931.204352070152
62 th iteration with cost  8929.647546745786
63 th iteration with cost  8928.17049375186
64 th iteration with cost  8926.768227479171
65 th iteration with cost  8925.436138340954
66 th iteration with cost  8924.169944533298
67 th iteration with cost  8922.965666243595
68 th iteration with cost  8921.819602074187
69 th iteration with cost  8920.72830747237
70 th iteration with cost  8919.688574980015
71 th iteration with cost  8918.697416135063
72 th iteration with cost  8917.752044874427
73 th iteration with cost  8916.849862302506
74 th iteration with cost  8915.98844270363
75 th iteration with cost  8915.165520687953
76 th iteration with cost  8914.378979371631
77 th iteration with cost  8913.626839501218
78 th iteration with cost  8912.907249441016
79 th iteration with cost  8912.21847594959
80 th iteration with cost  8911.558895678412
81 th iteration with cost  8910.926987332132
82 th iteration with cost  8910.321324435046
83 th iteration with cost  8909.740568653533
84 th iteration with cost  8909.183463628835
85 th iteration with cost  8908.64882927828
86 th iteration with cost  8908.13555652708
87 th iteration with cost  8907.642602435786
88 th iteration with cost  8907.16898569185
89 th iteration with cost  8906.713782436087
90 th iteration with cost  8906.276122397676
91 th iteration with cost  8905.855185313205
92 th iteration with cost  8905.450197607584
93 th iteration with cost  8905.060429316558
94 th iteration with cost  8904.68519123166
95 th iteration with cost  8904.323832250944
96 th iteration with cost  8903.975736919327
97 th iteration with cost  8903.640323144251
98 th iteration with cost  8903.3170400732
99 th iteration with cost  8903.005366120933

In [11]:
for i in range(len(slopes)):
    print("Slope for ",i,"th feature is ",slopes[i])

Slope for  0 th feature is  -0.9051944815092405
Slope for  1 th feature is  0.668605342022142
Slope for  2 th feature is  -0.1509377291007227
Slope for  3 th feature is  0.7967257297446271
Slope for  4 th feature is  -2.08778318076616
Slope for  5 th feature is  2.3850686868992232
Slope for  6 th feature is  0.10869690128518013
Slope for  7 th feature is  -2.907873170407203
Slope for  8 th feature is  2.1520144849656075
Slope for  9 th feature is  -1.2938247285701296
Slope for  10 th feature is  -2.2239126669218554
Slope for  11 th feature is  0.5801892490299635
Slope for  12 th feature is  -4.264479920597307
Slope for  13 th feature is  22.6770807747901

In [24]:
def predict(x, slopes):
    pred = np.zeros(len(x))
    for i in range(len(x)):
        this_pred = slopes[len(slopes)-1]
        for j in range(len(slopes)-1):
            this_pred += slopes[j]* x.iloc[i,j]
        pred[i] = this_pred
    return pred

In [25]:
y_pred = predict(pd.read_csv("test_boston_x_test.csv"),slopes)

In [27]:
np.savetxt("boston_data_predictions.csv", y_pred, delimiter=",")